spring.application.name=datingApp

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/datingapp}
spring.datasource.username=${DB_USERNAME:datingapp}
spring.datasource.password=${DB_PASSWORD:datingapp}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/datingapp}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.admin.fail-fast=false
spring.kafka.consumer.group-id=dating-app
spring.kafka.consumer.auto-offset-reset=earliest

# JWT
app.jwt.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007}
app.jwt.access-token-ttl=PT15M
app.jwt.refresh-token-ttl=P30D

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.storage.path=${STORAGE_PATH:./uploads}
